site_name: ErsatzTV
nav:
  - 'Quick Start':
    - 'Install ErsatzTV': 'user-guide/install.md'
    - 'Add Media Items': 'user-guide/add-media-items.md'
    - 'Create Collections': 'user-guide/create-collections.md'
    - 'Create Channels': 'user-guide/create-channels.md'
    - 'Configure Clients': 'user-guide/configure-clients.md'
  - 'Advanced':
    - 'Filler': 'user-guide/filler.md'
    - 'Local Libraries': 'user-guide/local-libraries.md'
    - 'Search': 'user-guide/search.md'
    - 'Sample Schedules': 'user-guide/sample-schedules.md'
  - 'Thanks': 'thanks.md'
theme:
  name: material
  palette:
    scheme: slate
  logo: images/ersatztv-square-logo.png
  favicon: images/favicon-32x32.png
  features:
    - navigation.expand
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2020 - 2023 Jason Dove
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hHaJm3yGy6
      name: ErsatzTV on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/jasongdove/ErsatzTV
      name: ErsatzTV on GitHub
    - icon: fontawesome/regular/heart
      link: https://github.com/sponsors/jasongdove
      name: Sponsor on GitHub
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.me/jasongdove
      name: Donate on PayPal
google_analytics:
  - UA-193031642-1
  - auto
